# Generated by Django 3.1.4 on 2020-12-11 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_dummy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dummy',
        ),
    ]
